; used only when non js pure scheme
(increxample)
;(set! fn "())")
;(set! fn "z")
(set! centerx 0.0)
(set! centery 0.0)
(set! width 2.5)
(set! iterations 5)
(set! colortype '(grid na))
(set! fn "(* (+ 1 i) (tan z))")
;(set! fn "(sqrt (- 1.0 (* x x)))")
;(set! fn "(abs (* (cos (* 6 pi x)) (exp (- (^ (* 2.0 x) 2)))))")
;(set! fn "(* x y)")
;(set! fn "(* 0.01 x)")
(plotmain)
